environment:
  matrix:
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
    # - MSYS2_ARCH: i686
    #   MSYSTEM: MINGW32

build_script:
  - '%APPVEYOR_BUILD_FOLDER%\appveyor.bat'

deploy: off

artifacts:
  - path: dist
    name: xqemu
    type: zip
