name: Build xemu-win64-toolchain

on:
  push:
    paths:
      - '.github/workflows/build-xemu-win64-toolchain.yml'
      - 'ubuntu-win64-cross/**'
  pull_request:
    paths:
      - '.github/workflows/build-xemu-win64-toolchain.yml'
      - 'ubuntu-win64-cross/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: xemu-project/xemu-win64-toolchain

jobs:
  build-image:
    name: Build and Publish Image
    if: github.repository_owner == 'xemu-project'
    runs-on: ubuntu-latest
    steps:
      - name: Clone tree
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Extract image metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title=xemu-win64-toolchain
            org.opencontainers.image.description=Toolchain and libraries for building xemu Windows releases
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=ref,event=branch
            type=sha
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v5
        with:
          context: ubuntu-win64-cross
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
